# -*- coding: utf-8 -*-
# -*- encoding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################

from openerp.osv import fields, osv

from mx import DateTime
#import netsvc
import time
from openerp.tools.translate import _

 
class stock_production_lot(osv.osv):
    _inherit = 'stock.production.lot'


    _columns = {
        'fecha_retimbrado':fields.date('fecha_retimbrado'),
        'ci_numero': fields.char('Numero', size=64, help="Numero"),
        'ci_planta': fields.char('Planta', size=64, help="Planta"),
        'ci_situacion': fields.char('Situacion', size=64, help="Situacion"),
        'ci_marca': fields.char('Marca', size=64, help="Marca"),
        'ci_tipo': fields.char('Tipo', size=64, help="Tipo"),
        'ci_carga': fields.char('Carga', size=64, help="Carga"),
        'ci_eficacia': fields.char('Eficacia', size=64, help="Eficacia"),
        'ci_numero_industria': fields.char('Numero Industria', size=64, help="Numero Industria"),
        'ci_fecha_fabricacion':fields.date('Fecha Fabricacion', help="Extintores  - Fecha Fabricacion"), 
        'ci_fecha_1_ret':fields.date('Fecha 1 Retimbrado', help="Extintores  - Fecha 1 Retimbrado"), 
        'ci_fecha_2_ret':fields.date('Fecha 2 Retimbrado', help="Extintores  - Fecha 2 Retimbrado"), 
        'ci_fecha_3_ret':fields.date('Fecha 3 Retimbrado', help="Extintores  - Fecha 3 Retimbrado"), 
        'ci_manguera': fields.char('Manguera', size=64, help="Extintores  - Manguera"),
        'ci_altura_extintor': fields.char('Altura Extintor', size=64, help="Extintores  - Altura Extintor"),
        'ci_boquilla_lanza': fields.char('Boquilla Lanza', size=64, help="Extintores  - Boquilla Lanza"),
        'ci_senal': fields.char('Senal', size=64, help="Extintores  - Senal"),
        'ci_peso_presion': fields.char('Peso/Presion', size=64, help="Extintores  - Peso/Presion"),
        'ci_observaciones': fields.text('Observaciones', help="Observaciones"),
        'ci_armario': fields.char('Armario', size=64, help="Bies - Armario"),
        'ci_manguera_diametro': fields.char('Manguera mm/m', size=64, help="Bies - Manguera mm/m"),
        'ci_manguera_longitud': fields.char('Manguera Long', size=64, help="Bies - Manguera Long"),
        'ci_manguera_estado': fields.char('Manguera Estado', size=64, help="Bies - Manguera Estado"),
        'ci_devanadera': fields.char('Devanadera', size=64, help="Bies - Devanadera"),
        'ci_manometro_estado': fields.char('Manometro Estado', size=64, help="Bies - Manometro Estado"),
        'ci_manometro_presion': fields.char('Manometro Presion', size=64, help="Bies - Manometro Presion"),
        'ci_valvula': fields.char('Valvula', size=64, help="Bies - Valvula"),
        'ci_racor': fields.char('Racor', size=64, help="Bies - Racor"),
        'ci_lanza': fields.char('Lanza', size=64, help="Bies - Lanza"),
        'ci_cristal': fields.char('Cristal', size=64, help="Bies - Cristal"),
        'ci_fecha_nueva':fields.date('Fecha Nueva', help="Bies - Fecha Nueva"), 
        'ci_fecha_timbre':fields.date('Fecha Timbre', help="Bies - Fecha Timbre"), 
        'ci_cent_marca': fields.char('Marca', size=64, help="Deteccion Automatica Y Alarma Manual De Incendios - Marca"),
        'ci_cent_modelo': fields.char('Modelo', size=64, help="Deteccion Automatica Y Alarma Manual De Incendios - Modelo"),
        'ci_cent_num_zona': fields.char('N Zonas', size=64, help="Deteccion Automatica Y Alarma Manual De Incendios - N Zonas"),
        'ci_cent_zona_extincion': fields.char('Zonas Extincion', size=64, help="Deteccion Automatica Y Alarma Manual De Incendios - Zonas Extincion"),
        'ci_cent_pilotos': fields.char('Pilotos', size=64, help="Deteccion Automatica Y Alarma Manual De Incendios - Pilotos"),
        'ci_cent_reles': fields.char('Reles', size=64, help="Deteccion Automatica Y Alarma Manual De Incendios - Reles"),
        'ci_cent_zumbador': fields.char('Zumbador', size=64, help="Deteccion Automatica Y Alarma Manual De Incendios - Zumbador"),
        'ci_cent_zonas_lazos_reserva': fields.char('Zonas/Lazos Reservas', size=64, help="Deteccion Automatica Y Alarma Manual De Incendios - Zonas/Lazos Reservas"),
        'ci_cent_tipo_baterias': fields.char('Tipo Baterias', size=64, help="Deteccion Automatica Y Alarma Manual De Incendios - Tipo Baterias"),
        'ci_cent_unidades': fields.char('Unidades', size=64, help="Deteccion Automatica Y Alarma Manual De Incendios - Unidades"),
        'ci_cent_estado_carga': fields.char('Estado Carga', size=64, help="Deteccion Automatica Y Alarma Manual De Incendios - Estado Carga"),
        'ci_cent_red_independiente': fields.char('Red Independiente', size=64, help="Deteccion Automatica Y Alarma Manual De Incendios - Red Independiente"),
        'ci_del_ubicacion': fields.char('Ubicacion', size=64, help="Deteccion Automatica Y Alarma Manual De Incendios - Ubicacion"),
        'ci_del_zonas_lazos_reserva': fields.char('Zona o Lanzo Num', size=64, help="Deteccion Automatica Y Alarma Manual De Incendios - Zona o Lanzo Num"),
        'ci_del_detector_numero': fields.char('Detector Numero', size=64, help="Deteccion Automatica Y Alarma Manual De Incendios - Detector Numero"),
        'ci_del_detector_estado': fields.char('Detector Estado', size=64, help="Deteccion Automatica Y Alarma Manual De Incendios - Detector Estado"),
        'ci_del_pulsador_numero': fields.char('Pulsador Numero', size=64, help="Deteccion Automatica Y Alarma Manual De Incendios - Pulsador Numero"),
        'ci_del_pulsador_estado': fields.char('Pulsador Estado', size=64, help="Deteccion Automatica Y Alarma Manual De Incendios - Pulsador Estado"),
        'ci_del_indicador_numero': fields.char('Indicador Numero', size=64, help="Deteccion Automatica Y Alarma Manual De Incendios - Indicador Numero"),
        'ci_del_indicador_estado': fields.char('Indicador Estado', size=64, help="Deteccion Automatica Y Alarma Manual De Incendios - Indicador Estado"),
        'ci_del_sirena_numero': fields.char('Sirena/Campana Numero', size=64, help="Deteccion Automatica Y Alarma Manual De Incendios - Sirena/Campana Numero"),
        'ci_del_sirena_estado': fields.char('Sirena/Campana Estado', size=64, help="Deteccion Automatica Y Alarma Manual De Incendios - Sirena/Campana Estado"),
        'ci_del_retenedor_estado': fields.char('Retenedor Estado', size=64, help="Deteccion Automatica Y Alarma Manual De Incendios - Retenedor Estado"),
        'ci_del_retenedor_numero': fields.char('Retenedor Numero', size=64, help="Deteccion Automatica Y Alarma Manual De Incendios - Retenedor Numero"),
        'ci_jock_marca': fields.char('Marca', size=64, help="Grupo De Presion Contra Incendios - Bomba Jockey - Marca"),
        'ci_jock_modelo': fields.char('Modelo', size=64, help="Grupo De Presion Contra Incendios - Bomba Jockey - Modelo"),
        'ci_jock_tipo': fields.char('Tipo', size=64, help="Grupo De Presion Contra Incendios - Bomba Jockey - Tipo"),
        'ci_jock_potencia': fields.char('Potencia', size=64, help="Grupo De Presion Contra Incendios - Bomba Jockey - Potencia"),
        'ci_jock_caudal': fields.char('Caudal', size=64, help="Grupo De Presion Contra Incendios - Bomba Jockey - Caudal"),
        'ci_jock_altura': fields.char('Altura', size=64, help="Grupo De Presion Contra Incendios - Bomba Jockey - Altura"),
        'ci_jock_rpm': fields.char('r.p.m', size=64, help="Grupo De Presion Contra Incendios - Bomba Jockey - r.p.m"),
        'ci_jock_horas_inicial': fields.char('Cuenta Horas Inicial', size=64, help="Grupo De Presion Contra Incendios - Bomba Jockey - Cuenta Horas Inicial"),
        'ci_jock_horas_final': fields.char('Cuenta Horas Final', size=64, help="Grupo De Presion Contra Incendios - Bomba Jockey - Cuenta Horas Final"),
        'ci_elec_bomba_marca': fields.char('Marca', size=64, help="Grupo De Presion Contra Incendios - Bomba Principal Electrica - Bomba - Marca"),
        'ci_elec_bomba_modelo': fields.char('Modelo', size=64, help="Grupo De Presion Contra Incendios - Bomba Principal Electrica - Bomba - Modelo"),
        'ci_elec_bomba_caudal': fields.char('Caudal', size=64, help="Grupo De Presion Contra Incendios - Bomba Principal Electrica - Bomba - Caudal"),
        'ci_elec_bomba_altura': fields.char('Altura', size=64, help="Grupo De Presion Contra Incendios - Bomba Principal Electrica - Bomba - Altura"),
        'ci_elec_motor_marca': fields.char('Marca', size=64, help="Grupo De Presion Contra Incendios - Bomba Principal Electrica - Motor - Marca"),
        'ci_elec_motor_modelo': fields.char('Modelo', size=64, help="Grupo De Presion Contra Incendios - Bomba Principal Electrica - Motor - Modelo"),
        'ci_elec_motor_potencia': fields.char('Potencia', size=64, help="Grupo De Presion Contra Incendios - Bomba Principal Electrica - Motor - Potencia"),
        'ci_elec_motor_rpm': fields.char('RMP', size=64, help="Grupo De Presion Contra Incendios - Bomba Principal Electrica - Motor - RMP"),
        'ci_elec_motor_automatico': fields.char('Automatico', size=64, help="Grupo De Presion Contra Incendios - Bomba Principal Electrica - Motor - Automatico"),
        'ci_elec_motor_consumo': fields.char('Consumo', size=64, help="Grupo De Presion Contra Incendios - Bomba Principal Electrica - Motor - Consumo"),
        'ci_elec_motor_horas_inicial': fields.char('Cuenta Horas Inicial', size=64, help="Grupo De Presion Contra Incendios - Bomba Principal Electrica - Motor - Cuenta Horas Inicial"),
        'ci_elec_motor_horas_final': fields.char('Cuenta Horas Final', size=64, help="Grupo De Presion Contra Incendios - Bomba Principal Electrica - Motor - Cuenta Horas Final"),
        'ci_dies_bomba_marca': fields.char('Marca', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Bomba -Marca"),
        'ci_dies_bomba_modelo': fields.char('Modelo', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Bomba -Modelo"),
        'ci_dies_bomba_tipo_num': fields.char('Tipo', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Bomba -Tipo"),
        'ci_dies_bomba_caudal': fields.char('Caudal', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Bomba -Caudal"),
        'ci_dies_bomba_altura': fields.char('Altura', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Bomba -Altura"),
        'ci_dies_motor_marca': fields.char('Marca', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor -Marca"),
        'ci_dies_motor_modelo': fields.char('Modelo', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor -Modelo"),
        'ci_dies_motor_tipo_num': fields.char('Tipo', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor -Tipo"),
        'ci_dies_motor_potencia': fields.char('Potencia', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor -Potencia"),
        'ci_dies_motor_rpm': fields.char('rpm', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor -rpm"),
        'ci_dies_motor_horas_inicial': fields.char('Cuenta Horas Inicial', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor -Cuenta Horas Inicial"),
        'ci_dies_motor_horas_final': fields.char('Cuenta Horas Final', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor -Cuenta Horas Final"),
        'ci_dies_filaceite_marca': fields.char('Marca', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor - Filtro Aceite Marca"),
        'ci_dies_filaceite_modelo': fields.char('Modelo', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor - Filtro Aceite Modelo"),
        'ci_dies_filaire_marca': fields.char('Marca', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor - Filtro Aire  Marca"),
        'ci_dies_filaire_modelo': fields.char('Modelo', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor - Filtro Aire  Modelo"),
        'ci_dies_filgasoil_marca': fields.char('Marca', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor - Filtro Gasoil   Marca"),
        'ci_dies_filgasoil_modelo': fields.char('Modelo', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor - Filtro Gasoil   Modelo"),
        'ci_dies_nivel_gasoil': fields.char('Gasoil', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor - NivelesGasoil"),
        'ci_dies_nivel_aceite': fields.char('Aceite', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor - NivelesAceite"),
        'ci_dies_bateria_marca': fields.char('Marca', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor - Baterias Marca"),
        'ci_dies_bateria_unidad': fields.char('Unidades', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor - Baterias Unidades"),
        'ci_dies_bateria_tipo': fields.char('Tipo', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor - Baterias Tipo"),
        'ci_dies_bateria_estado': fields.char('Estado', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor - Baterias Estado"),
        'ci_regpres_jock_arranque': fields.char('Jocker Arranque', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor - Regulacion presostatos Jocker Arranque"),
        'ci_regpres_jock_parada': fields.char('Jocker Parada', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor - Regulacion presostatos Jocker Parada"),
        'ci_regpres_elec_arranque': fields.char('Electrica Arranque', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor - Regulacion presostatos Electrica Arranque"),
        'ci_regpres_elec_parada': fields.char('Electrica Parada', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor - Regulacion presostatos Electrica Parada"),
        'ci_regpres_dies_arranque': fields.char('Diesel Arranque', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor - Regulacion presostatos Diesel Arranque"),
        'ci_regpres_dies_parada': fields.char('Diesel Parada', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor - Regulacion presostatos Diesel Parada"),
        'ci_deppre_marca': fields.char('Marca', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor - Deposito de presion Marca"),
        'ci_deppre_modelo': fields.char('Modelo', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor - Deposito de presion Modelo"),
        'ci_deppre_tipo': fields.char('Tipo', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor - Deposito de presion Tipo"),
        'ci_deppre_capacidad': fields.char('Capacidad', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor - Deposito de presion Capacidad"),
        'ci_deppre_presion': fields.char('Presion', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor - Deposito de presion Presion"),
        'ci_elem_caudalimetro': fields.char('Caudalimetro', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor - Elementos Caudalimetro"),
        'ci_elem_valvula_seguridad': fields.char('Valvula de seguridad', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor - Elementos Valvula de seguridad"),
        'ci_elem_tarada': fields.char('Tarada ', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor - Elementos Tarada "),
        'ci_elem_colect_prueba': fields.char('Colector prueba', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor - Elementos Colector prueba"),
        'ci_elem_cuadro_control': fields.char('Cuadro control', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor - Elementos Cuadro control"),
        'ci_elem_bypass': fields.char('By-pass de entrada red', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor - Elementos By-pass de entrada red"),
        'ci_elem_valvulas': fields.char('Valvulas', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor - Elementos Valvulas"),
        'ci_elem_desague': fields.char('Desague conducido', size=64, help="Grupo De Presion Contra Incendios - Bomba Diesel - Motor - Elementos Desague conducido"),
        'ci_curpre_elec_0_caudal': fields.char('Electrica 0% Caudal', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Electrica 0% Caudal"),
        'ci_curpre_elec_0_htotal': fields.char('Electrica 0% H Total', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Electrica 0% H Total"),
        'ci_curpre_elec_0_consumo': fields.char('Electrica 0% H Consumo', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Electrica 0% H Consumo"),
        'ci_curpre_elec_0_voltaje': fields.char('Electrica 0% Voltaje', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Electrica 0% Voltaje"),
        'ci_curpre_elec_0_rpm': fields.char('Electrica 0% RPM', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Electrica 0% RPM"),
        'ci_curpre_elec_50_caudal': fields.char('Electrica 50% Caudal', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Electrica 50% Caudal"),
        'ci_curpre_elec_50_htotal': fields.char('Electrica 50% H Total', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Electrica 50% H Total"),
        'ci_curpre_elec_50_consumo': fields.char('Electrica 50% H Consumo', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Electrica 50% H Consumo"),
        'ci_curpre_elec_50_voltaje': fields.char('Electrica 50% Voltaje', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Electrica 50% Voltaje"),
        'ci_curpre_elec_50_rpm': fields.char('Electrica 50% RPM', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Electrica 50% RPM"),
        'ci_curpre_elec_100_caudal': fields.char('Electrica 100% Caudal', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Electrica 100% Caudal"),
        'ci_curpre_elec_100_htotal': fields.char('Electrica 100% H Total', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Electrica 100% H Total"),
        'ci_curpre_elec_100_consumo': fields.char('Electrica 100% H Consumo', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Electrica 100% H Consumo"),
        'ci_curpre_elec_100_voltaje': fields.char('Electrica 100% Voltaje', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Electrica 100% Voltaje"),
        'ci_curpre_elec_100_rpm': fields.char('Electrica 100% RPM', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Electrica 100% RPM"),
        'ci_curpre_elec_140_caudal': fields.char('Electrica 140% Caudal', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Electrica 140% Caudal"),
        'ci_curpre_elec_140_htotal': fields.char('Electrica 140% H Total', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Electrica 140% H Total"),
        'ci_curpre_elec_140_consumo': fields.char('Electrica 140% H Consumo', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Electrica 140% H Consumo"),
        'ci_curpre_elec_140_voltaje': fields.char('Electrica 140% Voltaje', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Electrica 140% Voltaje"),
        'ci_curpre_elec_140_rpm': fields.char('Electrica 140% RPM', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Electrica 140% RPM"),
        'ci_curpre_dies_0_caudal': fields.char('Diesel 0% Caudal', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Diesel 0% Caudal"),
        'ci_curpre_dies_0_htotal': fields.char('Diesel 0% H Total', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Diesel 0% H Total"),
        'ci_curpre_dies_0_consumo': fields.char('Diesel 0% H Consumo', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Diesel 0% H Consumo"),
        'ci_curpre_dies_0_voltaje': fields.char('Diesel 0% Voltaje', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Diesel 0% Voltaje"),
        'ci_curpre_dies_0_rpm': fields.char('Diesel 0% RPM', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Diesel 0% RPM"),
        'ci_curpre_dies_50_caudal': fields.char('Diesel 50% Caudal', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Diesel 50% Caudal"),
        'ci_curpre_dies_50_htotal': fields.char('Diesel 50% H Total', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Diesel 50% H Total"),
        'ci_curpre_dies_50_consumo': fields.char('Diesel 50% H Consumo', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Diesel 50% H Consumo"),
        'ci_curpre_dies_50_voltaje': fields.char('Diesel 50% Voltaje', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Diesel 50% Voltaje"),
        'ci_curpre_dies_50_rpm': fields.char('Diesel 50% RPM', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Diesel 50% RPM"),
        'ci_curpre_dies_100_caudal': fields.char('Diesel 100% Caudal', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Diesel 100% Caudal"),
        'ci_curpre_dies_100_htotal': fields.char('Diesel 100% H Total', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Diesel 100% H Total"),
        'ci_curpre_dies_100_consumo': fields.char('Diesel 100% H Consumo', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Diesel 100% H Consumo"),
        'ci_curpre_dies_100_voltaje': fields.char('Diesel 100% Voltaje', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Diesel 100% Voltaje"),
        'ci_curpre_dies_100_rpm': fields.char('Diesel 100% RPM', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Diesel 100% RPM"),
        'ci_curpre_dies_140_caudal': fields.char('Diesel 140% Caudal', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Diesel 140% Caudal"),
        'ci_curpre_dies_140_htotal': fields.char('Diesel 140% H Total', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Diesel 140% H Total"),
        'ci_curpre_dies_140_consumo': fields.char('Diesel 140% H Consumo', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Diesel 140% H Consumo"),
        'ci_curpre_dies_140_voltaje': fields.char('Diesel 140% Voltaje', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Curvas de presion-caudal -Diesel 140% Voltaje"),
        'ci_curpre_dies_140_rpm': fields.char('Diesel 140% RPM', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Aljibe -Diesel 140% RPM"),
        'ci_alji_dimensiones': fields.char('Dimensiones', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Aljibe -Dimensiones"),
        'ci_alji_capacidad': fields.char('Capacidad', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Aljibe -Capacidad"),
        'ci_alji_electrovalvula': fields.char('Electovalvula Entrada', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Aljibe -Electovalvula Entrada"),
        'ci_alji_sondas_nivel': fields.char('Sondas de Nivel', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Aljibe -Sondas de Nivel"),
        'ci_alji_valvula_flotador': fields.char('Valvula Flotador', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Aljibe -Valvula Flotador"),
        'ci_acom_llave_abierta': fields.char('Llave Abierta', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Acometida -Llave Abierta"),
        'ci_acom_precintada': fields.char('Precintada', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Acometida -Precintada"),
        'ci_acom_independiente': fields.char('Independiente', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Acometida -Independiente"),
        'ci_acom_contador': fields.char('Contador', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Acometida -Contador"),
        'ci_acom_pulgadas': fields.char('Pulgadas', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Acometida -Pulgadas"),
        'ci_cuabom_ventilacion': fields.char('Ventilacion', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Cuarto de bombas -Ventilacion"),
        'ci_cuabom_limpieza': fields.char('Limpieza', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Cuarto de bombas -Limpieza"),
        'ci_cuabom_rociadores': fields.char('Rociadores', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Cuarto de bombas -Rociadores"),
        'ci_cuabom_deteccion': fields.char('Deteccion', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Cuarto de bombas -Deteccion"),
        'ci_cuabom_senal_central': fields.char('Senal a Central', size=64, help="Grupo De Presion Contra Incendios - Revision del Grupo de Presion Contra Incendios - Cuarto de bombas -Senal a Central"),
        'ci_ubicacion': fields.char('Ubicacion', size=64, help="Alumbrado De Emergencia - Ubicacion"),
        'ci_elemento': fields.char('Elementos', size=64, help="Alumbrado De Emergencia - Elementos"),
        'ci_lumenes': fields.char('Lumenes', size=64, help="Alumbrado De Emergencia - Lumenes"),
        'ci_estado': fields.char('Estado', size=64, help="Alumbrado De Emergencia - Estado"),
        'ci_accesibilidad': fields.char('Accesibilidad', size=64, help="Hidrantes - Accesibilidad"),
        'ci_racores': fields.char('Racores', size=64, help="Hidrantes - Racores"),
        'ci_juntas': fields.char('Juntas', size=64, help="Hidrantes - Juntas"),
        'ci_tapas': fields.char('Tapas', size=64, help="Hidrantes - Tapas"),
        'ci_drenaje': fields.char('Drenaje', size=64, help="Hidrantes - Drenaje"),
        'ci_engrase': fields.char('Engrase', size=64, help="Hidrantes - Engrase"),
        'ci_caudal': fields.char('Caudal', size=64, help="Hidrantes - Caudal"),
        'ci_senalizacion': fields.char('Senalizacion', size=64, help="Hidrantes - Senalizacion"),
        'ci_distancia_caseta': fields.char('Distancia a la caseta', size=64, help="Hidrantes - Casetas Exteriores - Distancia a la caseta"),
        'ci_casext_numero': fields.char('Numero', size=64, help="Hidrantes - Casetas Exteriores - Numero"),
        'ci_casext_ubicacion': fields.char('Ubicacion', size=64, help="Hidrantes - Casetas Exteriores - Ubicacion"),
        'ci_casext_accesibilidad': fields.char('Accesibilidad', size=64, help="Hidrantes - Casetas Exteriores - Accesibilidad"),
        'ci_casext_llave_hidrante': fields.char('Llave Hidrante', size=64, help="Hidrantes - Casetas Exteriores - Llave Hidrante"),
        'ci_casext_1_lanza_70mm': fields.char('Lanza 1 70 mm', size=64, help="Hidrantes - Casetas Exteriores - Hidrantes 80mm - Lanzas - 1 Lanza 70 mm"),
        'ci_casext_2_lanza_80mm': fields.char('Lanza 2 80mm', size=64, help="Hidrantes - Casetas Exteriores - Hidrantes 80mm - Lanzas - 2 Lanza 80mm"),
        'ci_casext_mang45_fecfabrica':fields.date('Fecha Fabricacion', help="Hidrantes - Casetas Exteriores - Hidrantes 80mm - Mangueras 45mm - Fecha Fabricacion"), 
        'ci_casext_mang45_fecretimbrado':fields.date('Fecha Retimbrado', help="Hidrantes - Casetas Exteriores - Hidrantes 80mm - Mangueras 45mm - Fecha Retimbrado"), 
        'ci_casext_mang70_fecfabrica':fields.date('Fecha Fabricacion', help="Hidrantes - Casetas Exteriores - Hidrantes 80mm - Mangueras 70mm - Fecha Fabricacion"), 
        'ci_casext_mang70_fecretimbrado':fields.date('Fecha Retimbrado', help="Hidrantes - Casetas Exteriores - Hidrantes 80mm - Mangueras 70mm - Fecha Retimbrado"), 
        'ci_casext_bifurcacion_siamesa': fields.char('Bifurcacion', size=64, help="Hidrantes - Casetas Exteriores - Bifurcacion"),
        'ci_casext_reduccion': fields.char('Reduccion de 70-45mm', size=64, help="Hidrantes - Casetas Exteriores - Reduccion de 70-45mm"),
        'ci_toma_siamesa': fields.char('Toma Siamesa', size=64, help="Columna Seca - Toma Siamesa"),
        'ci_racores_tampones': fields.char('Racores Tapones', size=64, help="Columna Seca - Racores Tapones"),
        'ci_cadenas': fields.char('Cadenas', size=64, help="Columna Seca - Cadenas"),
        'ci_tapa_cristal': fields.char('Tapa Cristal', size=64, help="Columna Seca - Tapa Cristal"),
        'ci_cierre': fields.char('Cierre', size=64, help="Columna Seca - Cierre"),
        'ci_rotulo': fields.char('Rotulo', size=64, help="Columna Seca - Rotulo"),
        'ci_valvula_seccionamiento': fields.char('Valvula Seccionamiento', size=64, help="Columna Seca - Valvula Seccionamiento"),
        'ci_puscont_ubicacion': fields.char('Ubicacion', size=64, help="Rociadores Automaticos Y Puestos De Control - Puestos de Control - Ubicacion"),
        'ci_puscont_marca': fields.char('Marca', size=64, help="Rociadores Automaticos Y Puestos De Control - Puestos de Control - Marca"),
        'ci_puscont_pulgada': fields.char('Pulgadas', size=64, help="Rociadores Automaticos Y Puestos De Control - Puestos de Control - Pulgadas"),
        'ci_puscont_presion_arriba': fields.char('Presion Arriba', size=64, help="Rociadores Automaticos Y Puestos De Control - Puestos de Control - Presion Arriba"),
        'ci_puscont_presion_abajo': fields.char('Presion Abajo', size=64, help="Rociadores Automaticos Y Puestos De Control - Puestos de Control - Presion Abajo"),
        'ci_puscont_detector_flujo': fields.char('Detector Flujo', size=64, help="Rociadores Automaticos Y Puestos De Control - Puestos de Control - Detector Flujo"),
        'ci_puscont_gong': fields.char('Gong', size=64, help="Rociadores Automaticos Y Puestos De Control - Puestos de Control - Gong"),
        'ci_puscont_valvulas': fields.char('Valvulas', size=64, help="Rociadores Automaticos Y Puestos De Control - Puestos de Control - Valvulas"),
        'ci_puscont_senal_central': fields.char('Senal Central', size=64, help="Rociadores Automaticos Y Puestos De Control - Rociadores Automaticos - Senal Central"),
        'ci_rocaut_ubicacion': fields.char('Ubicacion', size=64, help="Rociadores Automaticos Y Puestos De Control - Rociadores Automaticos - Ubicacion"),
        'ci_rocaut_diametro': fields.char('Diametro', size=64, help="Rociadores Automaticos Y Puestos De Control - Rociadores Automaticos - Diametro"),
        'ci_rocaut_tipo': fields.char('Tipo', size=64, help="Rociadores Automaticos Y Puestos De Control - Rociadores Automaticos - Tipo"),
        'ci_rocaut_tipo_numero': fields.char('Tipo Numero', size=64, help="Rociadores Automaticos Y Puestos De Control - Rociadores Automaticos - Tipo Numero"),
        'ci_rocaut_color': fields.char('Color', size=64, help="Rociadores Automaticos Y Puestos De Control - Rociadores Automaticos - Color"),
        'ci_rocaut_punpru_ubicacion': fields.char('Punto Prueba Ubicacion', size=64, help="Rociadores Automaticos Y Puestos De Control - Rociadores Automaticos - Punto Prueba Ubicacion"),
        'ci_rocaut_punpru_presion': fields.char('Punto Prueba Presion', size=64, help="Rociadores Automaticos Y Puestos De Control - Rociadores Automaticos - Punto Prueba Presion"),
        'ci_cent_zona_reserva': fields.char('Reserva', size=64, help="Sistema De Extincion Automatico - Caracteristicas de la Central - Reserva"),
        'ci_cent_mandos_control': fields.char('Mandos Contro', size=64, help="Sistema De Extincion Automatico - Caracteristicas de la Central - Mandos Contro"),
        'ci_cent_linea_cableado': fields.char('Lineas Cableado', size=64, help="Sistema De Extincion Automatico - Caracteristicas de la Central - Lineas Cableado"),
        'ci_fal_marca': fields.char('Marca', size=64, help="Sistema De Extincion Automatico - Caracteristicas Fuente de Alimentacion - Marca"),
        'ci_fal_modelo': fields.char('Modelo', size=64, help="Sistema De Extincion Automatico - Caracteristicas Fuente de Alimentacion - Modelo"),
        'ci_fal_unidades': fields.char('Unidades', size=64, help="Sistema De Extincion Automatico - Caracteristicas Fuente de Alimentacion - Unidades"),
        'ci_fal_tipo_baterias': fields.char('Tipo Baterias', size=64, help="Sistema De Extincion Automatico - Caracteristicas Fuente de Alimentacion - Tipo Baterias"),
        'ci_fal_estado_carga': fields.char('Estado Carga', size=64, help="Sistema De Extincion Automatico - Caracteristicas Fuente de Alimentacion - Estado Carga"),
        'ci_sdi_tipo': fields.char('Tipo', size=64, help="Sistema De Extincion Automatico - Elementos del Sistema de Distribucion - Tipo"),
        'ci_sdi_modelo': fields.char('Modelo', size=64, help="Sistema De Extincion Automatico - Elementos del Sistema de Distribucion - Modelo"),
        'ci_sdi_ubicacion': fields.char('Ubicacion', size=64, help="Sistema De Extincion Automatico - Elementos del Sistema de Distribucion - Ubicacion"),
        'ci_sdi_num_zona': fields.char('Zona Numero', size=64, help="Sistema De Extincion Automatico - Elementos del Sistema de Distribucion - Zona Numero"),
        'ci_sdi_detector_num': fields.char('Detector Numero', size=64, help="Sistema De Extincion Automatico - Elementos del Sistema de Distribucion - Detector Numero"),
        'ci_sdi_detector_estado': fields.char('Detectos Estado', size=64, help="Sistema De Extincion Automatico - Elementos del Sistema de Distribucion - Detectos Estado"),
        'ci_sdi_pul_bloqueo_num': fields.char('Pul Bloqueo Numero', size=64, help="Sistema De Extincion Automatico - Elementos del Sistema de Distribucion - Pul Bloqueo Numero"),
        'ci_sdi_pul_bloqueo_estado': fields.char('Pul Bloqueo Estado', size=64, help="Sistema De Extincion Automatico - Elementos del Sistema de Distribucion - Pul Bloqueo Estado"),
        'ci_sdi_pul_disparo_num': fields.char('Pul Disparo Numero', size=64, help="Sistema De Extincion Automatico - Elementos del Sistema de Distribucion - Pul Disparo Numero"),
        'ci_sdi_pul_disparo_estado': fields.char('Pul Disparo Estado', size=64, help="Sistema De Extincion Automatico - Elementos del Sistema de Distribucion - Pul Disparo Estado"),
        'ci_sdi_cartel_num': fields.char('Cartel Numero', size=64, help="Sistema De Extincion Automatico - Elementos del Sistema de Distribucion - Cartel Numero"),
        'ci_sdi_cartel_estado': fields.char('Cartel Estado', size=64, help="Sistema De Extincion Automatico - Elementos del Sistema de Distribucion - Cartel Estado"),
        'ci_sdi_sirena_num': fields.char('Sirena Numero', size=64, help="Sistema De Extincion Automatico - Elementos del Sistema de Distribucion - Sirena Numero"),
        'ci_sdi_sirena_estado': fields.char('Sirena Estado', size=64, help="Sistema De Extincion Automatico - Elementos del Sistema de Distribucion - Sirena Estado"),
        'ci_aex_tipo_agente': fields.char('Tipo Agente', size=64, help="Sistema De Extincion Automatico - Agente de Extincion - Tipo Agente"),
        'ci_aex_marca_valvuleria': fields.char('Marca Valvuleria', size=64, help="Sistema De Extincion Automatico - Agente de Extincion - Marca Valvuleria"),
        'ci_aex_soportacion': fields.char('Soportacion', size=64, help="Sistema De Extincion Automatico - Agente de Extincion - Soportacion"),
        'ci_aex_situacion': fields.char('Situacion', size=64, help="Sistema De Extincion Automatico - Agente de Extincion - Situacion"),
        'ci_aex_sistema_pesaje': fields.char('Sistema de Pesaje', size=64, help="Sistema De Extincion Automatico - Agente de Extincion - Sistema de Pesaje"),
        'ci_aex_direccionables': fields.char('Direccionales', size=64, help="Sistema De Extincion Automatico - Agente de Extincion - Direccionales"),
        'ci_aex_antiterremotos': fields.char('Antiterremotos', size=64, help="Sistema De Extincion Automatico - Agente de Extincion - Antiterremotos"),
        'ci_aex_ubicacion': fields.char('Ubicacion', size=64, help="Sistema De Extincion Automatico - Agente de Extincion - Ubicacion"),
        'ci_aex_cilindro_num': fields.char('Cilindro Numero', size=64, help="Sistema De Extincion Automatico - Agente de Extincion - Cilindro Numero"),
        'ci_aex_cilindro_peso': fields.char('Cilindro Peso', size=64, help="Sistema De Extincion Automatico - Agente de Extincion - Cilindro Peso"),
        'ci_aex_carga': fields.char('Carga', size=64, help="Sistema De Extincion Automatico - Agente de Extincion - Carga"),
        'ci_aex_peso_total': fields.char('Peso Total', size=64, help="Sistema De Extincion Automatico - Agente de Extincion - Peso Total"),
        'ci_aex_fecha_carga':fields.date('Fecha Carga', help="Sistema De Extincion Automatico - Agente de Extincion - Fecha Carga"), 
        'ci_aex_presion': fields.char('Presion', size=64, help="Sistema De Extincion Automatico - Agente de Extincion - Presion"),
        'ci_aex_fecha_retimbrado':fields.date('Fecha Retimbrado', help="Sistema De Extincion Automatico - Agente de Extincion - Fecha Retimbrado"), 
        'ci_aex_fecha_fabricacion':fields.date('Fecha Fabricacion', help="Sistema De Extincion Automatico - Agente de Extincion - Fecha Fabricacion"), 
        'ci_aex_tipo_disparo': fields.char('Tipo Disparo', size=64, help="Sistema De Extincion Automatico - Agente de Extincion - Tipo Disparo"),
        'ci_aex_difusores': fields.char('Difusores', size=64, help="Sistema De Extincion Automatico - Agente de Extincion - Difusores"),
        'ci_cent_concentracion': fields.char('Concentracion ppm', size=64, help="Sistema De Monoxido - Caracteristicas de la Central - Concentracion ppm"),
        'ci_cent_arranque_manual': fields.char('Arranque Manual', size=64, help="Sistema De Monoxido - Caracteristicas de la Central - Arranque Manual"),
        'ci_cent_arranque_automatico': fields.char('Arranque Automatico', size=64, help="Sistema De Monoxido - Caracteristicas de la Central - Arranque Automatico"),
        'ci_cent_alarma': fields.char('Alarma', size=64, help="Sistema De Monoxido - Caracteristicas de la Central - Alarma"),
        'ci_sdi_marca_detectores': fields.char('Marca Detetores', size=64, help="Sistema De Monoxido - Elementos del Sistema de Distribucion - Marca Detetores"),
        'ci_sdi_fecha_caducidad_sensor':fields.date('Fecha Caducidad Sensor', help="Sistema De Monoxido - Elementos del Sistema de Distribucion - Fecha Caducidad Sensor"), 
        'ci_sdi_dettoma_num': fields.char('Det Toma Numero', size=64, help="Sistema De Monoxido - Elementos del Sistema de Distribucion - Det Toma Numero"),
        'ci_sdi_dettoma_estado': fields.char('Det/Toma Estado', size=64, help="Sistema De Monoxido - Elementos del Sistema de Distribucion - Det/Toma Estado"),
        'ci_sdi_motor_num': fields.char('Motores Numero', size=64, help="Sistema De Monoxido - Elementos del Sistema de Distribucion - Motores Numero"),
        'ci_sdi_motor_estado': fields.char('Motores Estado', size=64, help="Sistema De Monoxido - Elementos del Sistema de Distribucion - Motores Estado"),
        'ci_sdi_correas_num': fields.char('Correas Numero', size=64, help="Sistema De Monoxido - Elementos del Sistema de Distribucion - Correas Numero"),
        'ci_sdi_correas_estado': fields.char('Correas Estado', size=64, help="Sistema De Monoxido - Elementos del Sistema de Distribucion - Correas Estado"),
        'ci_sdi_engrase_num': fields.char('Engrase Numero', size=64, help="Sistema De Monoxido - Elementos del Sistema de Distribucion - Engrase Numero"),
        'ci_sdi_engrase_estado': fields.char('Engrase Estado', size=64, help="Sistema De Monoxido - Elementos del Sistema de Distribucion - Engrase Estado"),
        'ci_sdi_conductos_rejillas': fields.char('Conductos Rejillas', size=64, help="Sistema De Monoxido - Elementos del Sistema de Distribucion - Conductos Rejillas"),
        'ci_sdi_compuertas_num': fields.char('Compuertas Numero', size=64, help="Sistema De Monoxido - Elementos del Sistema de Distribucion - Compuertas Numero"),
        'ci_sdi_compuertas_estado': fields.char('Compuertas Estado', size=64, help="Sistema De Monoxido - Elementos del Sistema de Distribucion - Compuertas Estado"),
        'ci_mex_aut_marca': fields.char('Marca', size=64, help="Sistema De Monoxido - Modos Extraccion - Automatico - Marca"),
        'ci_mex_aut_intensidad': fields.char('Intensidad', size=64, help="Sistema De Monoxido - Modos Extraccion - Automatico - Intensidad"),
        'ci_mex_cont_marca': fields.char('Marca', size=64, help="Sistema De Monoxido - Modos Extraccion - Contador - Marca"),
        'ci_mex_cont_modelo': fields.char('Modelo', size=64, help="Sistema De Monoxido - Modos Extraccion - Contador - Modelo"),
        'ci_mex_guar_marca': fields.char('Marca', size=64, help="Sistema De Monoxido - Modos Extraccion - Guardamotor - Marca"),
        'ci_mex_guar_modelo': fields.char('Modelo', size=64, help="Sistema De Monoxido - Modos Extraccion - Guardamotor - Modelo"),
        'ci_mex_guar_regulacion': fields.char('Regulacion', size=64, help="Sistema De Monoxido - Modos Extraccion - Guardamotor - Regulacion"),
        'ci_mex_guar_ajustado': fields.char('Ajustado', size=64, help="Sistema De Monoxido - Modos Extraccion - Guardamotor - Ajustado"),
        'ci_mot_ubicacion': fields.char('Ubicacion', size=64, help="Sistema De Monoxido - Modos Extraccion - Motor - Ubicacion"),
        'ci_mot_modelo': fields.char('Modelo', size=64, help="Sistema De Monoxido - Modos Extraccion - Motor - Modelo"),
        'ci_mot_potencia': fields.char('Potencia', size=64, help="Sistema De Monoxido - Modos Extraccion - Motor - Potencia"),
        'ci_mot_tension': fields.char('Tension', size=64, help="Sistema De Monoxido - Modos Extraccion - Motor - Tension"),
        'ci_mot_intensidad': fields.char('Intensidad', size=64, help="Sistema De Monoxido - Modos Extraccion - Motor - Intensidad"),
        'ci_mot_rmp': fields.char('RPM', size=64, help="Sistema De Monoxido - Modos Extraccion - Motor - RPM"),
        'ci_mot_coseno': fields.char('Coseno', size=64, help="Sistema De Monoxido - Modos Extraccion - Motor - Coseno"),
        'ci_vent_marca': fields.char('Marca', size=64, help="Sistema De Monoxido - Modos Extraccion - Ventilador - Marca"),
        'ci_vent_modelo': fields.char('Modelo', size=64, help="Sistema De Monoxido - Modos Extraccion - Ventilador - Modelo"),
        'ci_vent_caudal': fields.char('Caudal', size=64, help="Sistema De Monoxido - Modos Extraccion - Ventilador - Caudal"),
        'ci_vent_potencia': fields.char('Potencia', size=64, help="Sistema De Monoxido - Modos Extraccion - Ventilador - Potencia"),
        'ci_vent_rpm': fields.char('RPM', size=64, help="Sistema De Monoxido - Modos Extraccion - Ventilador - RPM"),
        'ci_vent_presion': fields.char('Presion', size=64, help="Sistema De Monoxido - Modos Extraccion - Ventilador - Presion"),
        'ci_corr_marca': fields.char('Marca', size=64, help="Sistema De Monoxido - Modos Extraccion - Correas - Marca"),
        'ci_corr_modelo': fields.char('Modelo', size=64, help="Sistema De Monoxido - Modos Extraccion - Correas - Modelo"),
        'ci_corr_numero': fields.char('Numero', size=64, help="Sistema De Monoxido - Modos Extraccion - Numero"),
        'ci_tipo_ventilacion': fields.char('Tipo Ventilacion', size=64, help="Sistema De Monoxido - Modos Extraccion - Correas - Tipo Ventilacion"),         
 
    }


  
stock_production_lot()

# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:

